### ISSUE TITLE
Images - Lazy Loading

### ISSUE THREAD

**Issue by zrothauser** [10up/Engineering-Best-Practices#103]
Splitting off the discussions from #101 into separate issues:

Do we want to recommend lazy loading images on image-heavy pages? 

@TheLastCicada mentioned in #101 that it can be "fraught with peril", see that discussion for more details.

**Comment by tlovett1** [comment]
I think it's worth mentioning lazy loading as a good technique, but I'm not sure we need to recommend it. @tddewey ?

**Comment by tddewey** [comment]
It's a technique, but I see it more often applied as a band-aid to try and reduce front-end load time. I'd prefer other optimizations first.

Additionally, some sites are better suited for it. The site that shows a huge list of image-heavy full articles may benefit more than a site that has one or two large images "above the fold."

I think lazy loading images is simply a technique. I'd suggest we write an internal docs page outlining the different implementations of lazy load (there are several) and which sites they were implemented on. A reference for us internally — not a best practice.

**Comment by TheLastCicada** [comment]
I'd agree with this approach.  I'd be ok with it in the best practices if it were clear when the right time to use it was and when the wrong time to use it was, but I don't feel like there's a real clear distinction always.

**Comment by ericmann** [comment]
Chiming in here as well, as someone who's implemented lazy loading on several large sites and published tutorials about the technique outside of the team. It's a great tool in certain cases, but that's usually when other (better) alternatives have failed or proven unavailable.

I agree with making it an internal doc about the approach, but not recommending it as a best practice. Suggest closing this with that resolution.

**Comment by zrothauser** [comment]
I agree with all the above - closing this out.
