### ISSUE TITLE
Commit message best practices

### ISSUE THREAD

**Issue by helen** [10up/Engineering-Best-Practices#109]
I just published [best practices for commit messages in WordPress core](https://make.wordpress.org/core/handbook/best-practices/commit-messages/), much of which is general commit message advice. This is mostly a placeholder issue so we add this to our own best practices at 10up, with some blog posts I plan on writing to go along with it.

**Comment by dsawardekar** [comment]
About the description part of Commit Messages, I like Caleb's recommendations from [here](https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message).
1. Why is this change necessary?
2. How does it address the issue?
3. What side effects does this change have?

Not all commits need this much detail. But it can be useful, particularly on Feature Branch merges.

**Comment by ericmann** [comment]
I would like to see that kind of detail on merge commits, but it might be asking a bit too much for run-of-the-mill commits. The more documentation we ask for in individual commit messages, the more time and effort they take to write, and the less often the occur.

For smaller change-to-change commits, a quick "I did X" message is usually sufficient and helps keep multiple commits coming quickly.

That said, I do like the general format from the core docs for feature merges (which are more akin to the SVN commits for core anyway).

**Comment by TheLastCicada** [comment]
Would love to see some commit message best practices in this doc that we can point to.  This comes up a lot and some guidance would be helpful.

**Comment by brandwaffle** [comment]
+1 to @TheLastCicada comment.

**Comment by tlovett1** [comment]
Would love to see a PR for this one.
