### ISSUE TITLE
Documentation section

### ISSUE THREAD

**Issue by tlovett1** [10up/Engineering-Best-Practices#11]
We need a section to explain how we document our code.

**Comment by DrewAPicture** [comment]
I've thought about this a little bit and I think we can just convert the Code Style sections into Code Style & Documentation, and then link both standards. There isn't currently an adopted documentation standard for JS, but most core devs seem to be leaning toward a hybrid of JavaDoc and JSDoc3.

**Comment by DrewAPicture** [comment]
PR incoming.
