### ISSUE TITLE
esc_js() description is inaccurate

### ISSUE THREAD

**Issue by helen** [10up/Engineering-Best-Practices#110]
The PHP security section currently says:

> `esc_js()` ensures that whatever is returned is safe to be printed within a JavaScript string.

This is not completely accurate. The inline docs in core continue on to say:

> It is intended to be used for inline JS (in a tag attribute, for example onclick="..."). Note that the strings have to be in single quotes.

Given that we should not be writing JS in this manner anymore, `esc_js()` should never be used. Escaping strings for JS use can be done using `json_encode()`, or better yet `wp_json_encode()` which does some sanity checking for non-UTF8 and handles different versions of PHP.

**Comment by tlovett1** [comment]
Can you make a PR?

**Comment by raphaelkross** [comment]
Hi @helenhousandi and @tlovett1 

I've just made a PR fixing the points reported by Helen, I hope it isn't a problem.

#118 

Kind Regards.
