### ISSUE TITLE
Is get_posts() still bad?

### ISSUE THREAD

**Issue by kingkool68** [10up/Engineering-Best-Practices#116]
As of WordPress 4.3.1 (and probably earlier) `get_posts()` sets `'no_found_rows'`to `true` which is recommended by your best practices. See https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-includes/post.php#L1900 

You can still pass in `'update_post_meta_cache' => false`, `'update_post_term_cache' => false`, and `'fields' => 'ids'` as needed.

**Comment by tlovett1** [comment]
Hmmm great question. The big thing I see is by default `suppress_filters` is set to true. Would be curious to hear what others think.

**Comment by nicoladj77** [comment]
I think that [this post](http://wordpress.stackexchange.com/questions/1753/when-should-you-use-wp-query-vs-query-posts-vs-get-posts) explains the differences between `WP_Query` and `get_posts()`   better than I could. I normally use `get_posts()` when I just need an array of posts and don't want to run filters, and WP_Query() for secondary loops, when I expect template tags to work.
![query_functions](https://cloud.githubusercontent.com/assets/333069/11075949/4b24b654-87f8-11e5-9fd6-4e4dd58dcf7e.png)

**Comment by kingkool68** [comment]
According to the WordPress VIP Best Practices (https://vip.wordpress.com/documentation/caching/uncached-functions/) `get_posts()` is not cached via Advanced Post Cache unless you explicitly set `'suppress_filters' => false`

Much like @nicoladj77 I use `get_posts()` whenever I want to get an array of posts to loop over without using template tags.

**Comment by tlovett1** [comment]
Really, using `get_posts` is fine as long as your specify `'suppress_filters' => false`. However, I still think it's easier to just use WP_Query. Not sure we want to change this.

**Comment by dana-ross** [comment]
I agree with @tlovett1 here. WP_Query works well out of the box, and we can pass extra parameters to make it even more efficient. From a _best practices_ perspective, I'd rather we steer clear of get_posts() as long as we need to pass a certain parameter before it's acceptable. We're fallible humans. We're not going to remember to disable filter suppression all the time.

I'd consider it more acceptable if we had a wrapper function that always added that parameter. But I don't want 10up going down the road of making our own incompatible version of the WordPress API.

**Comment by kingkool68** [comment]
I'm not part of 10up I was just curious and opening this issue caused me to do a little research. Thanks for the discussion all.

**Comment by dana-ross** [comment]
No worries, @kingkool68 . It was a great discussion.
