### ISSUE TITLE
Editor Config

### ISSUE THREAD

**Issue by jonathantneal** [10up/Engineering-Best-Practices#126]
Using an EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. EditorConfig files are easily readable and they work nicely with version control systems. This is especially useful when there are many of us pushing to one staging branch and we want to reduce as many conflicts as possible.

http://editorconfig.org/#download

I have been using these in many projects already and have only had positive experiences. Today, I just noticed it is not included in our best practices. Have you been using `.editorconfig`? Do you think something like my first paragraph could be a useful entry?

**Comment by westonruter** [comment]
BTW, there is one in WordPress Core: https://core.trac.wordpress.org/browser/trunk/.editorconfig

**Comment by d2s** [comment]
[EditorConfig](http://survivejs.com/webpack_react/linting_in_webpack/#editorconfig) allows you to maintain a consistent coding style across different IDEs and editors.

It is also useful for avoiding Markdown specific syntax problems:

``` ruby
# Markdown text files
[*.md]
trim_trailing_whitespace = false
```

**Comment by jonathantneal** [comment]
I took a small audit of this project and found that editor styles change regularly between very similar files.
- `_includes/header.html` vs `_includes/tweet-button.html` (tabs vs 2-spaces)
- `_includes/components/_syntax-highlighter.scss` vs `_includes/components/_template-header.scss` (tabs vs 2-spaces)
- `php.md` vs `_includes/markdown/PHP.md` (2-spaces vs 4-spaces)
- `index.md` vs `javascript.md` (final newline vs no final newline)

If I write an .editorconfig that follows this project’s most common patterns and touches the least amount of files, it looks like this:

``` ini
root = true

[*]
charset = utf-8
end_of_line = lf
indent_style = tab
trim_trailing_whitespace = true

[*.{md,yml}]
indent_size = 2
indent_style = space

[*.{css,html,md,js,scss}]
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

**Comment by morganestes** [comment]
+1 for EditorConfig in :allthethings:. Some IDEs have problems with their implementation (looking at you, PhpStorm :eyes:) in some cases, but overall a great tool for consistency in contributions.

**Comment by tlovett1** [comment]
+1000. Can someone write up a PR and propose a standard .editorconfig? Using what's in core might make sense.

**Comment by morganestes** [comment]
@tlovett1 I can work on a new section for the docs and use Core's .editorconfig as the example. 

It'll be a separate issue from #127, since that (and this issue) are related to applying it to the Best Practices docs themselves (so meta).

**Comment by tlovett1** [comment]
@morganestes that would be great. Thanks!

**Comment by tlovett1** [comment]
@morganestes any update on this?

**Comment by dsawardekar** [comment]
@tlovett1 PR is #143

**Comment by dana-ross** [comment]
PR #143 was merged. Closing this issue.
