### ISSUE TITLE
Remove markup from functions

### ISSUE THREAD

**Issue by emeaguiar** [10up/Engineering-Best-Practices#133]
I'll try to make sense here... I've always liked to keep PHP, HTML, CSS, and Javascript as separate as possible, I feel like code is cleaner, sometimes, however, it's difficult to separate HTML from PHP, specially within the loop its not uncommon to see thing like this:

``` PHP
function print_stuff() {
    $stuff = get_stuff();
    $output = '';
    foreach ( $stuff as $thingy ) {
        $output .= '<p>' . $stuff->data . '</p>';
    }
    echo $output;
}
```

Now, I realize we can just print the html instead of storing it in a variable, but, what I suggest is to keep as much html as possible in a separate file, so:

``` PHP
function print_stuff() {
    $stuff = get_stuff();
    foreach ( $stuff as $thingy ) {
        set_query_var( 'my_stuff', $thingy );
        get_template_part( 'stuff' );
    }
}
```

``` PHP
<p><?php echo $my_stuff->data; ?></p>
```

Thoughts? Pros? Cons?

**Comment by dana-ross** [comment]
I prefer to use templates for as much as possible. In your example, I'd honestly just pass $stuff to the template. Most templating languages have some looping construct. And if you're using PHP as your templating language, then you're set.

This came up in #92 as well.

**Comment by nicholasio** [comment]
I'd rather not mess with query vars and just use include in combination with locale_template.

``` php
function print_stuff() {
    $stuff = get_stuff();
    foreach ( $stuff as $thingy ) {
        include locate_template( 'stuff.php' );
    }
}
```

The problem with get_template_part is that it creates a new scope and thus your local variables can't be accessed through the partial. By using include directly, you don't create a new scope and thus, your variables are in the same scope as the file you have included.

**Comment by dana-ross** [comment]
That's exactly why I like get_template_part(). I prefer to limit the set of variables available to the template to as small a scope as possible.

It's not so much of an issue at 10up. But I've seen templates get way out of hand, duplicating database lookups that already happened elsewhere in the code, using unsanitized input, and so on. It's safer to tell a front-end developer "you have variables $x, $y, and $z available. If you need anything else, let's work together to get it in scope".

get_template_part() is as close as we get to a proper templating language without leaving PHP.

**Comment by jonathantneal** [comment]
I, too, desire to keep PHP, HTML, CSS, and JS as separate as possible, @emeaguiar. Thanks for bringing this up.

@daveross, in @nicholasio’s example, is `$stuff` being within a function scope it so that a back-end developer can still tell a front-end developer "you have variable ($stuff or...) $x, $y, and $z available" ? If so, what are the advantages or disadvantages to this vs `set_query_var`?

**Comment by drebbits** [comment]
It's not really much of a trouble to set query vars, and adding a limitation as to what the template could access provides additional layer of security—preventing almost any variable to be executed inside the template. Even in Underscore.js templating, it needs to pass the object which will be used in the template being called.

**Comment by tlovett1** [comment]
I think we are all in agreement we like to separate HTML from PHP. However, I do think people get carried away with this. Sometimes a line of HTML in your PHP is much cleaner than the work around. Not a huge fan of `set_query_var` in that context. It feels forced, and whatever is set will be there in the query for other templates.

**Comment by stevegrunwell** [comment]
I second TL's view on going _too_ far in removing markup; there are also (albeit minor) performance considerations to consider when we're over-using `get_template_part()` or `locate_template()`, especially in a loop.
