### ISSUE TITLE
Switch markdown engine to Kramdown

### ISSUE THREAD

**Issue by zrothauser** [10up/Engineering-Best-Practices#135]
The project is currently set up to use Redcarpet, instead the default for Github Pages, Kramdown.

Github Pages will only support Kramdown on May 1st:
https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/

To go along with this, the only highlighter supported in Github Pages now is Rouge:
https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors

I found that switching to Kramdown forces PHP codeblocks to start with the PHP tag "<?php", or else the syntax highlighting does not work. From looking through the docs quickly, it looks most examples do this already, but it would be worth a thorough check of everything before switching.

**Comment by tlovett1** [comment]
Thanks for doing this research Zack! Can you create a PR?

**Comment by zrothauser** [comment]
This is updated in #137
