### ISSUE TITLE
Versioning css and js files to bust CDN and browser cache?

### ISSUE THREAD

**Issue by TheLastCicada** [10up/Engineering-Best-Practices#136]
I skimmed through and I didn't find anything about how to version js and css code in WordPress to bust CDN and browser caches when deploying updates.  Something like adding ?ver=0.1.5 to the end of the enqueue URL so that the CDN picks it up as a new asset.  I see this as confusing for new engineers all the time and it'd be great to have a best practice to point to.

**Comment by tlovett1** [comment]
Agree this should be required. WP actually supports a parameter for versioning assets.

**Comment by jonbellah** [comment]
Agree.

Generally, we use the `{THEME}_VERSION` constant, found by default in wp-make, and attach it to all of the assets we're loading through `wp_enqueue_script()` and `wp_enqueue_style()`.

If no one has an issue with that approach, then I write up a quick PR.

**Comment by tlovett1** [comment]
Sounds right to me.

**Comment by stevegrunwell** [comment]
@TheLastCicada have we made progress getting AAD available publicly? It would be great to be able to skip the version constants altogether and instead dynamically bust caches for assets that aren't given explicit versions.
