### ISSUE TITLE
Headings out of order

### ISSUE THREAD

**Issue by RachelRVasquez** [10up/Engineering-Best-Practices#149]
Was browsing the Best Practices and noticed the heading heiarchy currently skips H2's and goes straight from H1 to H3s and onward. If we want to follow a11y and [WP best practices](https://make.wordpress.org/themes/handbook/review/accessibility/required/#headings), headings should not skip numbers.

https://10up.github.io/Engineering-Best-Practices/markup/#accessibility

<img width="788" alt="screen shot 2016-09-23 at 12 04 54 am" src="https://cloud.githubusercontent.com/assets/10246844/18773901/886628e0-8121-11e6-9770-e852d82fb45f.png">

Not sure how we'd want to resolve this - moving all headings up one number?

**Comment by ericmann** [comment]
I think we originally _did_ have H2s, but everything got moved in one (or more) of some refactorings to make the layout and navigation work properly. Shouldn't be any major impact to bumping things up a level, though, but someone should make the change locally and test first.

**Comment by RachelRVasquez** [comment]
Sure I can do that. Will take a look locally soon. 👍

**Comment by RachelRVasquez** [comment]
PR submitted. https://github.com/10up/Engineering-Best-Practices/pull/153 I've adjusted the styles so while the structure has changed, the underlined/bold weights still apply to where they applied on the live site. I didn't, however, change sizes. Not sure if we mind that the headings are slightly bigger than before or we want to change them to match what we currently have? Let me know. 👍

**Comment by RachelRVasquez** [comment]
Are we going to merge this one in or voting to skip this change?

**Comment by tlovett1** [comment]
Merged!
