### ISSUE TITLE
Do we implement Skip Links?

### ISSUE THREAD

**Issue by RachelRVasquez** [10up/Engineering-Best-Practices#150]
Was curious what our standards are for skip links or if we make that decision on a case by case basis? I personally will try to implement them if they're appropriate for the project and while it's never really mentioned as a requirement, it just seems like a handy thing to have implemented and doesn't take much time to add. Wanted to get everyone's thoughts on making this practice more common?

[Skip links are currently required](https://make.wordpress.org/themes/handbook/review/accessibility/required/#skip-links) for using the accessibility-ready tag in WP themes.

**Comment by jonbellah** [comment]
👍 I think skip links would be a great addition to the accessibility section under markup.

**Comment by Camwyn** [comment]
Agreed. I can't remember the last time I DIDN'T use them.

**Comment by RachelRVasquez** [comment]
Cool, I'll see if I can add a blurb to the existing a11y guidelines and submit a PR. 👍

**Comment by RachelRVasquez** [comment]
Submitted a PR and open for feedback on improvements. 😄 

https://github.com/10up/Engineering-Best-Practices/pull/154

**Comment by timwright12** [comment]
Assigning this to myself so I can update the a11y section

**Comment by pattonwebz** [comment]
Hey @timwright12, have you spent much time reworking the a11y section yet? 

Would it get in your way if I refreshed and reworked the section about the skip link from this old PR here: https://github.com/10up/Engineering-Best-Practices/pull/154?

**Comment by timwright12** [comment]
@pattonwebz If you want to spin up a new PR, that'd be cool. We retired that old one (I forget why), I think because there was a recent revamp to the a11y section and it didn't quit fit well anymore. If you want to take on this topic let's make sure it's not just skip links and rather, "Bypass Blocks" to align the content more accurately with WCAG 2.0

**Comment by timwright12** [comment]
Merged
