### ISSUE TITLE
Bug: Top Nav is wonky Looking

### ISSUE THREAD

**Issue by RachelRVasquez** [10up/Engineering-Best-Practices#155]
Looks like the top nav is a bit strange around where the logo is. 

![screen shot 2016-10-04 at 1 59 38 pm](https://cloud.githubusercontent.com/assets/10246844/19086164/11e6b860-8a3b-11e6-892e-0902ee438097.png)

Looks like the issue is coming from an nth-child margin right at `#page-header .top-nav .header-nav li:nth-child(4)`.

**Comment by RachelRVasquez** [comment]
After pinging the pattern library room, it looks like the "Migration" link was moved and was intentional.

I can submit a PR to fix, but the nav due to the Migration link shift looks uneven now from the left and the right sides. Is this how we want to keep it? Asking before I go through with the fix? Here's a screenshot of what it'd look like assuming Migration is where it should be now.

![screen shot 2016-10-04 at 5 31 22 pm](https://cloud.githubusercontent.com/assets/10246844/19093307/94e5f420-8a58-11e6-9715-96fabe412395.png)

**Comment by RachelRVasquez** [comment]
Submitted a PR: https://github.com/10up/Engineering-Best-Practices/pull/156 Hoping this should fix it, this works on my local.

Based on these two threads:
- https://github.com/jekyll/jekyll-help/issues/10
- http://stackoverflow.com/questions/9053066/sorted-navigation-menu-with-jekyll-and-liquid/9126294#9126294

**Comment by tlovett1** [comment]
Still broken

**Comment by RachelRVasquez** [comment]
@tlovett1 Yep I'm aware - was trying some other solutions locally and have yet to find the solution. I've been pulled into billable work for the week. Any chance we can grab someone else to take a gander?

**Comment by dkoo** [comment]
@tlovett1 @RachelRVasquez I tried fixing this with CSS and restored the sort by weight functionality (with actual incremental weights assigned to the pages). Also, I believe the header looks less off-center when "Migrations" is to the left of the logo, because of the varying lengths of the links. Please let me know if this works for you.

**Comment by dkoo** [comment]
<img width="1133" alt="screen shot 2016-10-11 at 11 28 23 am" src="https://cloud.githubusercontent.com/assets/2230142/19276892/dc407e24-8fa5-11e6-8b21-c17c585dbb0b.png">

**Comment by tlovett1** [comment]
@dkoo can you swap "tools" with "migrations"?

**Comment by dkoo** [comment]
@tlovett1 swapped: https://github.com/10up/Engineering-Best-Practices/pull/158

**Comment by RachelRVasquez** [comment]
@dkoo This is awesome! Looks good - thanks so much for lending a hand here. 😄
