### ISSUE TITLE
[Navigation] Header hides behind menu

### ISSUE THREAD

**Issue by emeaguiar** [10up/Engineering-Best-Practices#160]
When navigating through the site, going to any anchor will result in the title staying behind the menu, I think it would be a improvement to place the anchor in the title so we get more context as to what we're looking at. Specially if we link the best practices to someone else:

![navigation-hides](https://cloud.githubusercontent.com/assets/1379732/19354824/b344bcc2-912d-11e6-87f6-3358d05b8ec4.gif)

**Comment by RachelRVasquez** [comment]
PR submitted: https://github.com/10up/Engineering-Best-Practices/pull/161
