### ISSUE TITLE
Package/Dependency Management with Yarn

### ISSUE THREAD

**Issue by jonbellah** [10up/Engineering-Best-Practices#162]
A couple of days ago, Facebook announced a new package manager called [Yarn](https://code.facebook.com/posts/1840075619545360/yarn-a-new-package-manager-for-javascript/). Yarn allows engineers to continue utilizing the npm registry, but has some additional performance and security considerations built in.

Yarn also has the potential to be a single solution for javascript and front-end package/dependency management, [bridging the gap between Bower and npm](https://bower.io/blog/2016/using-bower-with-yarn/).

I know it's still new and fairly unproven, but I figured I would at least start the conversation.

**Comment by joshlevinson** [comment]
I've been using yarn since shortly after its release. Faster installs, no issues for me locally.
I've modified the 10up Redux DeployBot repo to use yarn; it's working great there!
I'll likely continue to use yarn on new DB setups. 👍 from me!

**Comment by tlovett1** [comment]
Yarn looks really promising. I realize it uses npm behind the scenes but it seems too early to all out replace npm.

**Comment by jonbellah** [comment]
Bumping this thread, now that Bower has officially been deprecated: https://github.com/bower/bower/issues/2298

Will put together a PR soon to remove Bower from our toolset, with a separate PR to include Yarn.

**Comment by ericmann** [comment]
As a Bower contributor, this makes me sad :'( But @JonBellah, that's definitely the way to go.

**Comment by timwright12** [comment]
Closing this out to file a new issue around updating the docs to reflect NPM for dependency management
