### ISSUE TITLE
Update schema.org section for JSON-LD

### ISSUE THREAD

**Issue by dana-ross** [10up/Engineering-Best-Practices#168]
Google now recommends encoding schema.org microdata using JSON-LD (https://developers.google.com/search/docs/guides/intro-structured-data#markup-formats-and-placement).

This also makes the markup easier to read & maintain.

Let's update the schema.org section of our Best Practices to include this, and make sure the examples get updated as well.

**Comment by zanematthew** [comment]
Adding a reference to the Structured Data Testing Tool https://search.google.com/structured-data/testing-tool

**Comment by tlovett1** [comment]
+1

**Comment by dana-ross** [comment]
Old issue. Already addressed in #197 . Closing.
