### ISSUE TITLE
Caching WP_Query objects is a bad idea

### ISSUE THREAD

**Issue by pj-dave** [10up/Engineering-Best-Practices#170]
Hello 10up! In the [caching section](https://10up.github.io/Engineering-Best-Practices/php/#caching) you have several examples where you're saving WP_Query objects to the cache. We wrote a pretty detailed article about [why this is a bad idea](https://pressjitsu.com/blog/dont-cache-wp_query/), and why caching the complete HTML output or post IDs is a much better option.

**Comment by tlovett1** [comment]
Totally agree. Would love to see a PR fixing this.
