### ISSUE TITLE
[Discussion] Cyclomatic Complexity Level in ESLint

### ISSUE THREAD

**Issue by kopepasah** [10up/Engineering-Best-Practices#186]
Is there a specific reason 10up choose a `complexity` level of `3` in `.eslint`? While I do agree, that the default of `20` is quite lenient, `3` seems a bit strict.

One might argue that the lower complexity enforces strictness and allows leniency on a per-file basis. However, I think the opposite practice (allow slight leniency and enforce strictness per-file) is more practical. The reason for this is in most cases this is how a developer would get over the strict complexity: `/* eslint-disable complexity */`, disabling `complexity` completely (not practical).

On the other hand, with a more lenient default `complexity` a developer could make `complexity` stricter where it makes since like so: `/*eslint complexity: [2, 3]*/` (e.g. helper methods, simple conditionals, et cetera).

My recommendation is to set the default `complexity` to somewhere near 6-8, allowing slight leniency.

**Comment by tlovett1** [comment]
I definitely agree. Although I don't have much experience with getting complexity warnings via ESLint. @fuhton any thoughts?

**Comment by timwright12** [comment]
Closing this out since we released the eslint config https://www.npmjs.com/package/@10up/eslint-config
