### ISSUE TITLE
Adding anchors to subsections

### ISSUE THREAD

**Issue by ryanwelcher** [10up/Engineering-Best-Practices#193]
When linking to sections of the Best Practices, it would be great to be able to target a subsection. For example, being able to link directly to the Caching section under Performance.

I'll get a PR submitted for this shortly

**Comment by dana-ross** [comment]
While I agree anchors would be great to have, you can link directly to a section now by setting the URL's fragment to the heading's id.

Since the markup contains `<h3 id="caching">Caching</h3>`, https://10up.github.io/Engineering-Best-Practices/php/#caching links directly to the Caching section.

**Comment by ryanwelcher** [comment]
:facepalm we'll just chalk that up to user error. Thanks!
