### ISSUE TITLE
Make subtitles linkable

### ISSUE THREAD

**Issue by nprasath002** [10up/Engineering-Best-Practices#209]
I am think it would be helpful to have subtitles linkable from a main section.
https://10up.github.io/Engineering-Best-Practices/php/

If it make sense i will go ahead and create a PR for this

**Comment by nprasath002** [comment]
Now i see the you can select the subtitles from the main menu and link it. Still a github style link that appears on page would be useful

**Comment by tlovett1** [comment]
Like a little link icon next to each header? That could definitely be useful!

**Comment by timwright12** [comment]
I can take this one.
