### ISSUE TITLE
Update JavaScript Best Practices

### ISSUE THREAD

**Issue by timwright12** [10up/Engineering-Best-Practices#214]

**Comment by dana-ross** [comment]
I think we can take out the Underscore recommendation. With ES6 we finally have all [the most popular features in the language itself](https://www.reindex.io/blog/you-might-not-need-underscore/) and our new theme & plugin scaffolds use Babel.

**Comment by dana-ross** [comment]
Same with jQuery. A lot of the things we use it for (DOM element section, AJAX, DOM manipulation) are handled natively pretty well now.

We might want to document a preferred way to do `fetch()` in IE11.

**Comment by adamsilverstein** [comment]
👍 Great idea! Especially if we include resources like @daveross's  link above to help people learn the modern equivalents.

**Comment by ivankruchkoff** [comment]
It's worth having a discussion of which javascript we do want to support.

 If it's only ES6, but there are some browsers that don't support it, we still need to transpile / polyfill.

If we are transpiling / polyfilling, why arbitrarily stop at ES6?

Should we use the latest approved ES standard, ES2017? Or include ES Next too? 

e.g. https://github.com/tc39/proposals/blob/master/finished-proposals.md

On the CSS side of things, we did/do use vendor prefixed non standard CSS.

It's also important to mark the things that ES whatever don't give you that utility libraries do, e.g. https://lodash.com/docs/4.17.5#cloneDeep

**Comment by ivankruchkoff** [comment]
My 2c: ES Next, webpack, and try your hardest to avoid a util library

**Comment by dana-ross** [comment]
We totally could use newer standards with Babel. My only concern there is reliable references & training materials. ES6 is pretty established right now and 10up engineers get access to Wes Bos's class if they ask.

I don't think we need to spell out what libraries offer beyond what ECMAScript supports natively, but some guidance on selecting libraries would be helpful.

**Comment by dana-ross** [comment]
1. Prefer libraries with strong community adoption and support
2. Prefer libraries available through npm
3. Prefer libraries that focus on a few specific roles vs an entire framework or "grab bag" of features
4. Avoid libraries written by Dave Ross

**Comment by ivankruchkoff** [comment]
MDN has very high quality documentation, see the following:

**ES2016/ES7**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**ES2017/ES8**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

In the WP space, we use the platform/language docs https://codex.wordpress.org/Function_Reference/ and http://php.net/manual/en/. Why treat javascript differently?

**Comment by timwright12** [comment]
We're going to start moving to newer standards, but for best practice we still need some things in there for older code. I have a line item to revamp this section. Definitely open to feedback and back and forth on this thread.

**Comment by christianc1** [comment]
jQuery equivalent to the underscore to native resource @daveross linked to above:
http://youmightnotneedjquery.com/

**Comment by christianc1** [comment]
Additionally, depending on the ES standard we support, as we introduce new features as part of our best practices, we should reference the challenges the feature was introduced to solve (as applicable).  This will probably involved expanding the *Design Patterns* section, and correlating new javascript features to best practices around design patterns.

It will require some knowledge of common javascript conventions that result in difficult to maintain code.  We're familiar with potential pitfalls by now and this is a good opportunity to not only update our best practices with new javascript features, but also update recommendations on conventions. 

A good example is the introduction of `async/await`.  This feature was introduced to improve readability and clarity around nested promises or long promise chains and make it easier to write declarative javascript.  

Contrived Ex.
```javascript
const getPostAuthorFirstName = ( postId ) => {
  return new Promise( ( resolve, reject ) => {
    fetch( `/posts/${postId}.json` )
      .then( response => response.json() )
      .then( post => {
        fetch( `/users/${post.authorId}.json` )
          .then( response => response.json() )
          .then( author => resolve( author.firstName ) )
        } );
  } );
}
```

would be functionally equivalent to:

```javascript
const getPostById = async ( postId ) => {
  const response = await fetch( `/posts/${postId}.json` );
  return response.json();
};

const getAuthorByPost = async ( post ) => {
  const response = await fetch( `/users/${post.authorId}.json` );
  return response.json();
};

const getPostAuthorFirstName = async ( postId ) => {
    const post   = await getPostById( postId );
    const author = await getAuthorByPost( post );
    return author.firstName;
};
```

I would argue the latter is much more readable, and makes it easier for an application to adhere to DRY principles.

Another example I can think of is State Immutability and Pure Functions.  There are a lot of Javascript Anti-patterns, probably too many to address, but if we hit the big ones, we'll be doing ourselves a big favor.

**Comment by tlovett1** [comment]
Great thread.

I don't think the solution is "write ES6 code" or "write ES Next Code". The answer is write the most readable/extensible/maintainable/performant code possible. It just so happens that ES6+ provides functionality that improves readable/extensible/maintainable/performance.

Again, I don't think the answer is use the newest feature for the sake of using the newest feature. Rather, just use the language features that are available.

All that said, I think we use Babel to transpile to the latest ES whatever that is.  Then we make some suggestions around useful language features that should be used e.g. await.

**Comment by timwright12** [comment]
Closing this out since we've made a lot of updates to the JS page and there hasn't been any discussion since April. We can open up a new thread if there are more issues that crop up.
