### ISSUE TITLE
Missing single quote in Cache Remote Requests Example

### ISSUE THREAD

**Issue by Faison** [10up/Engineering-Best-Practices#22]
Hi there,

Wasn't sure if me forking this repo would create a private fork or not, and this issue is so small that I decided it wouldn't hurt to just bring it up to someone who's already committing.

Basically, if you look at the code example in the section titled [Cache Remote Requests](http://10up.github.io/Engineering-Best-Practices/php/#cache-remote-requests), there's a line that looks like this:

`wp_cache_set( 'prefix_other_blog_posts, $posts, '', HOUR_IN_SECONDS );`

There's a closing single quote missing right after `prefix_other_blog_posts`.

Like I said, really small. If it is safe for me to fork this repo without exposing it to the world, let me know and I can send a pull request, otherwise this issue is in the file _includes/markdown/PHP.md on line 220.

Thanks,
Faison

**Comment by rachelbaker** [comment]
Fix in PR #23
