### ISSUE TITLE
NPM package versioning, lock files, and reproducible builds

### ISSUE THREAD

**Issue by JodiWarren** [10up/Engineering-Best-Practices#238]
Following on from some spirited discussion on Slack, I thought it might be productive to move discussion about best practices for frontend module versioning to here.

The aim of this discussion is to create a section which can provide a best practices guide to:

- Using NPM vs Yarn
- Committing a lock file
- When to update a package.json
- How precise to be with package versioning

This is important not only for other developers day-to-day work, but also for CI servers to reproduce identical builds.

**Comment by krisgale** [comment]
chiming in with my personal preference as to a reproducible, reliable method:

- have gulp or grunt write a file w/ a timestamp
- have functions.php consume the contents of that file and store a global variable
- have all calls to wp_enqueue_script and _style use that global for version number

this could be done in the existing theme scaffold,
and would ensure a fresh version every time assets are re-generated

**Comment by JodiWarren** [comment]
@krisgale I think that's a fine solution for static asset cache-busting, but it's a slightly different topic. 

The problem:
Without a lock file, running `npm install` or `yarn` will fetch the latest qualifying modules which match the versions specified in `package.json`.

Let's take this dependencies block as an example:
```
  "dependencies": {
    "example-module": "^4.17.2"
  }
```

Without a lock file, this will happily install the latest `example-module` version of `4.17.10` as it matches the semver range. This can be problematic if the third-party module author hasn't been particularly well-behaved about breaking changes, or you may have even been unwittingly relying on buggy behaviour in your code!

In the past, one solution to this was to use exact versioning. However, this would rely on the package manager being strict about versions, and would also not be helpful if using a git repo like Github.

This is where lock files come in. See the matching part of a `package-lock.json` file:
```
  "dependencies": {
    "example-module": {
      "version": "4.17.10",
      "resolved": "https://registry.npmjs.org/example-module/-/example-module-4.17.2.tgz",
      "integrity": "sha512-UejweD1pDoXu+AD825lWwp4ZGtSwgnpZxb3JDViD7StjQz+Nb/6l093lx4OQ0foGWNRoc19mWy7BzL+UAK2iVg=="
    }
  }
```
and the equivalent part of a `yarn.lock` file:

```
example-module@^4.17.10:
  version "4.17.10"
  resolved "https://registry.yarnpkg.com/example-module/-/example-module-4.17.10.tgz#1b7793cf7259ea38fb3661d4d38b3260af8ae4e7"
```

This will not only allow the package manager to make sure that you source the file from the same URL as when the lock file was created, but also to hash the contents of the file to make sure that you are actually getting the exact same file.

**Comment by krisgale-zz** [comment]
my recommendation: `"example-module": "4.17.2"` -- **be implicit** (no `^` or `~`)

**Comment by JodiWarren** [comment]
@krisgale as I mentioned above, this is purely relying on version number rather than anything more concrete. NPM and Yarn both now have the capability of much more reliable package resolution. We should be utilising that.

The discussion I wanted to have here is about:

1. Whether we recommend to use NPM or Yarn
2. That we should recommend committing a lock file
3. When to update the packages in a package.json
4. How precise to be with package versioning

It may be that exact versions are the right answer to point 4, but I would prefer that lock files solve that problem, and that semantic versioning allows for reasonable dependency updates in a controlled manner.

**Comment by ivankruchkoff** [comment]
https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md

> This file is intended to be committed into source repositories

**Comment by JodiWarren** [comment]
My personal feeling is:

- We should recommend the use of NPM. Nothing against Yarn, but NPM is more of a standard.
- We should absolutely commit the lock file. If a dependency is added or updated, the lock file should be committed alongside `package.json`
- Packages should be updated as part of a semi-regular dependency sweep. We can use [`npm outdated`](https://docs.npmjs.com/cli/outdated) to check what needs an update and [`npm update`](https://docs.npmjs.com/cli/update) to safely update within the semver range. It's the responsibility of the updater to make sure that there are no breaking changes.
- We should let NPM apply the default semver range when adding an item to `package.json`. The lock file will handle the precision of which source and source integrity, and having a semver range means that `npm outdated`/`npm update` will produce potentially useful results.
- CI servers should use [`npm ci`](https://docs.npmjs.com/cli/ci) for fast and reliable builds.

NPMs semver ranges can be referenced in [the documentation](https://docs.npmjs.com/misc/semver#versions). Be sure to read the [Advanced Ranges](https://docs.npmjs.com/misc/semver#advanced-range-syntax) section too.

**Comment by timwright12** [comment]
From a policy standpoint, we did make a decision to use NPM instead of Yarn, unless you're on a React project, and we do always check in the package lock file.

**Comment by dana-ross** [comment]
Yes, Yarn was our recommendation for a long time until npm caught up in terms of performance & features. We made a deliberate choice recently to return to npm.

**Comment by tlovett1** [comment]
My take and what we've discussed at Engineering Leadership:
* NPM over Yarn.
* Always always always commit lock files.
* `package.json` and `composer.json` should specify major versions but allow for bug fix upgrades. Specific version are a bad idea. What if a critical security fix is patched?

@timwright12 @daveross @cmmarslender did we ever get anywhere with package management best practices?

**Comment by timwright12** [comment]
^ that's the policy, but I don't see an area where it's written up

**Comment by timwright12** [comment]
@JodiWarren would you mind updating best practice docs with the info @tlovett1 outlined just so we have it somewhere? Ping me in slack and we can chat about where it might go.

**Comment by timwright12** [comment]
Closing this out because @daveross wrote it up https://10up.github.io/Engineering-Best-Practices/structure/#dependencies
