### ISSUE TITLE
Remove Modernizr on Markup section

### ISSUE THREAD

**Issue by smy315** [10up/Engineering-Best-Practices#239]
Modernizr (including HTML5Shiv) is no longer needed and I'm pretty sure that we don't use it on any of our projects. Can we completely remove this section (https://10up.github.io/Engineering-Best-Practices/markup/#html5-structural-elements#modernizr)? I can create a PR.

**Comment by dana-ross** [comment]
@timwright12 I'm good with removing this if you are. We can always pull in Modernizr if a project calls for classic IE or other browser support, but almost everything my teams work on is IE 11 and up.

**Comment by timwright12** [comment]
I'm not against removing the tool, but the concept of feature detection is still valid. @smy315 If you want to create a PR for that area, let's rewrite it to lean on the concept rather than the tool. We still run into some detection with stuff like exports.

**Comment by tlovett1** [comment]
I also thought Modernizr was obsolete but certainly could be wrong :)

**Comment by smy315** [comment]
PR: https://github.com/10up/Engineering-Best-Practices/pull/243

Replaced the content for Modernizr section with Feature Detection content. Was told that Modernizr is still utilized so it's included as a link for "feature detection libraries" instead of having a entire section for it.

**Comment by colorful-tones** [comment]
@smy315 PR looks good to me and makes sense as a new 10upper :)
