### ISSUE TITLE
suggestion: add wp_localize_script, explanation, benefits, links to how-to

### ISSUE THREAD

**Issue by krisgale-zz** [10up/Engineering-Best-Practices#241]
maybe too esoteric a thing? but considering the importance of i18n & related translation functions, as well as isolating presentation from data-preparation, i think it bears mention in the PHP chapter.

**Comment by tlovett1** [comment]
Hmm, not sure what you are getting at. `wp_localize_script` is definitely important and useful. Maybe create a PR?

**Comment by krisgale-zz** [comment]
background/context: used it on a project whereby i would have otherwise been 'dumping' json data wholesale within page content... suggestion to use `wp_localize_script` came up in code review, and when i went looking for information about it; saw it was not mentioned in our doc... i think a brief description of an example use-case for `wp_localize_script` may be warranted, with external links to additional examples & more information.
