### ISSUE TITLE
Consider renaming the "Structure" page to "Design"

### ISSUE THREAD

**Issue by helen** [10up/Engineering-Best-Practices#244]
This is coming out of #229 to add a section about privacy best practices (specifically user data right now, but could be more things). It doesn't really fit anywhere else because it's not language-specific like a lot of other security/privacy information, and I think `Design` does a good job of describing both things like file structure and other general engineering considerations.

**Comment by tlovett1** [comment]
I like this idea! Want to draft a PR?

**Comment by helen** [comment]
@tlovett1 Yep, see #262
