### ISSUE TITLE
Add note about possible VoiceOver list issue to CSS section

### ISSUE THREAD

**Issue by JodiWarren** [10up/Engineering-Best-Practices#282]
For problem and possible solutions see: https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html

Could just add a reference to above blog post, but I think it's worth detailing alongside the code snippet that fixes it.

**Comment by timwright12** [comment]
@JodiWarren Can you make a note about where this issue is on the site?

**Comment by JodiWarren** [comment]
@timwright12 Sorry for the lack of clarity - it's not to fix a problem on the site, it's to add a note about this potential problem for CSS authors.

**Comment by jonathantneal** [comment]
There’s a PostCSS plugin for that, too.

https://www.npmjs.com/package/postcss-list-style-safari-fix

**Comment by samikeijonen** [comment]
As I said in Slack, my opinion is that let it be by default. Then case by case check do we want CSS hack for rescuing Safari behaviour. From my experience we don't need this CSS hack very often.

Here is another [article about the lists and Safari and Voiceover](https://yatil.net/blog/much-ado-about-no-lists).

**Comment by timwright12** [comment]
@samikeijonen agreed, I'm going to close this one out
