### ISSUE TITLE
Sysadmin reads code, believes Batcache CAN cache URLs with query string

### ISSUE THREAD

**Issue by TheLastCicada** [10up/Engineering-Best-Practices#29]
I believe https://github.com/Automattic/batcache/blob/master/advanced-cache.php#L384 shows that batcache does cache full pages with query arguements, it just saves different query strings as unique pages (which is why you can defeat the cache and get a fresh page by adding ?new=yes at the end of a URL).  

I believe this is in conflict with line 190 in PHP.md:  

_"As Batcache does not cache calls for URLs with query strings or logged-in users (based on WordPress login cookies), you will need to make sure that your application design uses pretty URLs to really benefit from this caching layer."_

I'd like it if someone who actually does PHP development confirmed this for me.  

Also worth noting:  the version of batcache on Github is not the version we use - it is altered with many updates from Automattic based on WordPress.com needs.  We use the .org version https://wordpress.org/plugins/batcache/installation/

**Comment by tddewey** [comment]
That's my (somewhat newly revised) understanding as well. In fact, I recently talked to @tott to see if there was a way to make it _not_ independently cache a query string. Only option there is to hack it.

**Comment by tott** [comment]
That's correct. The wording is wrong. It should be "As Batcache does not cache calls for URLs with query strings effectively"

**Comment by TheLastCicada** [comment]
I dunno - to me it caches them effectively - if your page is http://example.com/index.php?1234 it will cache that page just like any other page.  However, http://example.com/index.php?4321 will be cached as a totally different page.  As long as every query string isn't unique, it will cache these pages just like any other page.  Basically the query string is part of the URL and each URL is cached as a unique page.

**Comment by tott** [comment]
What I meant is that it will create tons of cache variations for each query string which in most scenarios renders the cache useless

**Comment by TheLastCicada** [comment]
That's what I'd like to see elaborated on here.  I can think of many scenarios where a query string could be used and still get cached effectively.  The default permalinks for WordPress for one.  Also if a company is running a promotion and tracking the source of traffic, they could use a query string like ?promo=halloween&source=email.  In this example, the caching won't work as effectively as with no query string, but there will still be a significant set of users with that exact query string that will benefit from having that exact page cached.  It really depends on how the query strings are being used.  

Also, I'm told VIP handles query strings in their caching differently.  If we are writing specifically about what VIP does, we should be sure to separate that from Batcache in general.

**Comment by zamoose** [comment]
@TheLastCicada Don't most email campaigns utilize per-user hashes in their query strings to effectively check their click-through rates? (Not a huge issue other than to say that it makes @tott's point more salient.)

**Comment by aaronjorbin** [comment]
This is one area that varnish is superior to batcache. 

EDIT: I should specify, that the ability to group query arguments for caching (and only the ones you want) is what makes varnish superior.  Not that it is an outright better cache.  Both have strengths and weaknesses.

**Comment by TheLastCicada** [comment]
For an individual site, it seems like it shouldn't be too difficult to modify advanced-cache.php to have this same behavior.  I've been impressed by Varnish's TTFB recently and am looking forward to working with it more.  @aaronjorbin - do you have a Varnish WP plugin that you prefer for cache invalidation etc?

@zamoose I think all these points are valid, but I think we can make the language more clear in this document.  Creating a pull request for this has been on my list for a few days, but haven't gotten to it yet.
