### ISSUE TITLE
Add some more performance-related args to WP_Query section

### ISSUE THREAD

**Issue by helen** [10up/Engineering-Best-Practices#30]
We talk about `no_found_rows`, but in reality that only removes one query out of the **five** that `WP_Query` runs in its typical configuration. We should also document: `update_post_term_cache`, `update_post_meta_cache`, and `'fields' => 'ids'`.

**Comment by rachelbaker** [comment]
:+1:

**Comment by sc0ttkclark** [comment]
`'fields' => 'ids'` is my favorite :)

**Comment by tlovett1** [comment]
@helenhousandi mind writing a PR?

**Comment by ericmann** [comment]
Already been merged.
