### ISSUE TITLE
Broken links for Design section

### ISSUE THREAD

**Issue by jeffpaul** [10up/Engineering-Best-Practices#300]
The `Design` link in the header links to https://10up.github.io/Engineering-Best-Practices/structure/ (this resolves correctly) while the `Project Design` link in the Table of Contents links to https://10up.github.io/Engineering-Best-Practices/design/#top (this 404s).  I would normally open a PR to fix the `Project Design` link, but from a URL naming structure it looks like both should use the https://10up.github.io/Engineering-Best-Practices/design/ and update the docs foldering to use /design/ instead of /structure.  I'll leave it up to discussion here on the best approach to fix this.

**Comment by TheLastCicada** [comment]
This is still very broken and seems like an easy fix.....
