### ISSUE TITLE
Codex References in PHP Section

### ISSUE THREAD

**Issue by felipeelia** [10up/Engineering-Best-Practices#328]
## Describe the bug

As WordPress Codex is being discontinued in favor of DevHub and HelpHub, we should remove all references to Codex. I only found two of them:

### 1. In the [Performance](https://10up.github.io/Engineering-Best-Practices/php/#performance) section
> As noted in the WordPress **Codex** (along with a useful query flow chart), query_posts() isn’t meant to be used by plugins or themes. Due to replacing and possibly re-running the main query, query_posts() is not performant and certainly not an acceptable way of changing the main query.

This link actually already points to [query_posts()](https://developer.wordpress.org/reference/functions/query_posts/) DevHub page.

### 2. In the [Security](https://10up.github.io/Engineering-Best-Practices/php/#security) section
> There are many escaping situations not covered in this section. Everyone should explore the WordPress **codex** article on escaping output to learn more.

It seems this info now resides on [Plugins Handbook](https://developer.wordpress.org/plugins/security/securing-input/) and [Themes Handbook](https://developer.wordpress.org/themes/theme-security/data-sanitization-escaping/), although I think we can expect that Codex page being migrated to HelpHub soon.

## Steps to Reproduce

1. Visit https://10up.github.io/Engineering-Best-Practices/php/
2. Search for _Codex_

I'll be happy to send a PR if these changes really make sense.

**Comment by jeffpaul** [comment]
@felipeelia I concur, probably worthwhile to update our references away from the codex assuming the newer links provide valid info.

**Comment by felipeelia** [comment]
Thank you, @jeffpaul. I've opened a PR with the necessary changes, let me know if it needs any modification to be merged.
