### ISSUE TITLE
GitHub Security tab overtaken by our security.md file

### ISSUE THREAD

**Issue by jeffpaul** [10up/Engineering-Best-Practices#347]
**Describe the bug**
When you navigate to the [GitHub Security tab in this repo](https://github.com/10up/Engineering-Best-Practices/security/policy), you get served content from https://github.com/10up/Engineering-Best-Practices/blob/gh-pages/security.md since GitHub expects a `SECURITY.md` file for this page.

**Potential resolution**
Change the name of https://github.com/10up/Engineering-Best-Practices/blob/gh-pages/security.md to site-security.md and update references throughout the code?

**Comment by ciprianimike** [comment]
@jeffpaul I was going to work on this task but the bug is unconfirmed, even though the file for the site's security page is still called `security.md`.

Recorderd screen:
![security-tab](https://user-images.githubusercontent.com/5706607/97168272-715f6380-1788-11eb-8af4-06f29820d333.gif)

**Comment by jeffpaul** [comment]
@ciprianimike what do you see if you click on the Security Policy section of the Security tab?  Link should be: https://github.com/10up/Engineering-Best-Practices/security/policy

**Comment by ciprianimike** [comment]
@jeffpaul Issue replicated, please assign this to me, I'll fix it
