### ISSUE TITLE
Main nav on Best Practices is not displaying correctly.

### ISSUE THREAD

**Issue by gthayer** [10up/Engineering-Best-Practices#348]
**Describe the bug**
The navigation in the page header is being overlapped by the 10up logo. My guess is that a new item was added to the nav and the CSS needs to be updated.

**Steps to Reproduce**

1. Go to https://10up.github.io/Engineering-Best-Practices/
2. Click on look at the header.

**Expected behavior**
I wouldn't expect the logo to cover Design, or there to be so much space to the left of the logo. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6576646/95623722-c63e7280-0a43-11eb-83ac-37999c61163f.png)

**Environment information**
 - Device: Macbook
 - OS: MacOS 10.15.6
 - Browser and version: Chrome 85.0.4183.121

**Comment by jaz-on** [comment]
Hi I just saw that the menu is buggy, apparently it has already been reported here by @gthayer.

**Environment information**
- Device : laptop
- OS : W10
- Browser and version : Chrome 89.0.4389.72 (64 bits)

![screenshot-10up github io-2021 03 03-14_17_29](https://user-images.githubusercontent.com/56646501/109811706-7ac37580-7c2b-11eb-8c7e-adba8302c28b.png)
