### ISSUE TITLE
Add Web Vitals Best Practices

### ISSUE THREAD

**Issue by dainemawer** [10up/Engineering-Best-Practices#353]
**Describe the solution you'd like**
I would like to propose that we add a "Web Vitals" section to the 10up Best Engineering Practices site. The possible sub-navigation could work similarly to what I've suggested below:

**Web Vitals**
-  _Philosophy_ (what are Web Vitals, why should we care)
-  _Diagnosis_ (how we determine the current health of web vitals)
-  _Cumulative Layout Shift_ (best practices for fixing CLS)
-  _First Input Delay_ (best practices for fixing CLS)
-  _Largest Contentful Paint_ (best practices for fixing CLS)

**Additional context**
[Mike Bal's blog post on Web Vitals](https://internal.10up.com/blog/2021/01/05/required-reading-core-vitals-hits-googles-search-algorithm-and-what-to-do/)
[Daine Mawer's blog post on Web Vitals](https://internal.10up.com/blog/2021/01/08/required-reading-the-web-vitals-field-guide/)

**Comment by joesnellpdx** [comment]
I'm thinking more of a "Web Performance" tab and have Web Vitals be a primary section within and other bits can link out to their appropriate areas (like the existing sections for CSS / JS). So, like in web vitals, we may mention code splitting, and link to the performance best practice in JS - and explain the what/how there. 

Not sure that is the "right way" ... but what I'm thinking. 

@dainelmawer @tylercherpak

**Comment by tylercherpak** [comment]
Yeah I think have a broader "Web Performance" tab might make more sense in the long run as we add content here. We will also want to define what we mean by "Web Performance" which I assume it to be more front-end focused.

**Comment by dainemawer** [comment]
This sounds good to me, chaps. @joesnellpdx definitely agree that linking to existing sections is important. Theres still a few holes we need to fill there (in terms of writing documentation for code splitting) but I can try map this out so we know where to start. 

@tylercherpak agreed on the semantics behind "Web Performance" - I can write an introductory paragraph that mitigates this for sure. I'll set this site up locally and see what I can do!

**Comment by joesnellpdx** [comment]
@tylercherpak  @dainelmawer 

The only other concern (after seeing the updates I did yesterday) ... is where will this fit in the nav? We can cross that bridge when we get there, but may have to be part of this update. Content first priority.

**Comment by dainemawer** [comment]
Also noticed that when I cloned this repo down. I feel like some of those nav items should probably exist in a dropdown or something.

**Comment by joesnellpdx** [comment]
> Also noticed that when I cloned this repo down. I feel like some of those nav items should probably exist in a dropdown or something.

@dainelmawer I fix some of that here (not yet merged): https://github.com/10up/Engineering-Best-Practices/pull/349#issuecomment-789312040

What I'm considering as a solution for the addition of performance is to increase the nav break (hamburger  split) to a size where it al fits. Not 100%, but thinking might be the least LOE and get us where we need to be.

**Comment by jeffpaul** [comment]
@dainelmawer how this fits into the main nav aside (that's a separate problem we can solve), were you still planning to stub out a new section for this in a PR for others to comment on / add to?

**Comment by dainemawer** [comment]
@jeffpaul that's still the plan - I'm going to start working on this next week, hopefully, we can have something for comment / PR before 4/5!

**Comment by dainemawer** [comment]
@joesnellpdx @tylercherpak PR for this issue here: https://github.com/10up/Engineering-Best-Practices/pull/365
