### ISSUE TITLE
Visual Bugs on Submenus

### ISSUE THREAD

**Issue by smy315** [10up/Engineering-Best-Practices#361]
Some recent updates to the global header is causing the following visual bugs:

![Screen_Shot_2021-05-21_at_1_09_13_PM-2](https://user-images.githubusercontent.com/2092765/119182024-6891f000-ba40-11eb-8a70-59bbf7a8cb53.png)

![Screen_Shot_2021-05-21_at_1_09_00_PM-2](https://user-images.githubusercontent.com/2092765/119182036-6af44a00-ba40-11eb-91ca-4aa46b0a66c2.png)

![Screen_Shot_2021-05-21_at_1_09_07_PM-2](https://user-images.githubusercontent.com/2092765/119182042-6cbe0d80-ba40-11eb-9e44-60db5c421de4.png)

1) First Submenu  item not aligning with the rest
2) Extra space on the 7th menu items.

**Comment by joesnellpdx** [comment]
@tylercherpak no longer needed. Closing
