### ISSUE TITLE
Confusing WP_Query vs. get_posts()

### ISSUE THREAD

**Issue by JDGrimes** [10up/Engineering-Best-Practices#38]
On the PHP page under the [Effecient Database Queries section](https://github.com/10up/Engineering-Best-Practices/blob/gh-pages/_includes/markdown/PHP.md#efficient-database-queries) is this:

> WP_Query actually calls get_posts(); calling get_posts() directly bypasses a number of filters. Not sure whether you need these things or not? You probably don't.

I find that very confusing. It is actually the other way around: [the `get_posts()` function uses `WP_Query`](https://core.trac.wordpress.org/browser/tags/4.0/src/wp-includes/post.php#L1866). I assume that maybe you meant to refer to the _`WP_Query::get_posts()` method_.

**Comment by tlovett1** [comment]
You are correct. Thank you.
