### ISSUE TITLE
Unclear sentence re: including dependencies into VCS.

### ISSUE THREAD

**Issue by tddewey** [10up/Engineering-Best-Practices#52]
At the end of http://10up.github.io/Engineering-Best-Practices/structure/#modular-code:

"In these cases, the dependency, its version, and the reason for its inclusion in the project outside of a dependency manager."

I _think_ this sentence should read:

"In these cases, the dependency, its version, and the reason for its inclusion in the project outside of a dependency manager should be documented."

**Comment by tlovett1** [comment]
Yup, I think you're right.

**Comment by DrewAPicture** [comment]
+1

**Comment by NicoleGeissinger** [comment]
Yeah that makes sense to me Taylor.
