### ISSUE TITLE
WP_Query vs. get_posts() vs. query_posts + how WordPress handles queries

### ISSUE THREAD

**Issue by tlovett1** [10up/Engineering-Best-Practices#53]
Title says it all :)

**Comment by aymanrady** [comment]
@tlovett1 [https://codex.wordpress.org/Function_Reference/query_posts](https://codex.wordpress.org/Function_Reference/query_posts) does a pretty good job at explaining it

**Comment by nprasath002** [comment]
@tlovett1 
I already see a section that explains this. Is there anything you need to add there?
