### ISSUE TITLE
Responsive code blocks

### ISSUE THREAD

**Issue by tlovett1** [10up/Engineering-Best-Practices#63]
Right now, code samples are not readable on mobile. Lines are broken making code illegible.

**Comment by jonathantneal** [comment]
This is `pre` has `white-space` defined as `pre-wrap`. Updating normalize may resolve this.

I’d need to see why it’s defined this way before updating, as this was [an opinionated default in an older version](https://github.com/necolas/normalize.css/commit/a8edd0c5aa06b905e8e1550fd6a5c01e46375194).

If it’s a desired default, then a secondary solution is for `pre code` to have `white-space` defined as `pre`.

**Comment by tlovett1** [comment]
Thanks for weighing in @jonathantneal. @kdo any thoughts on what he said?

**Comment by kdo** [comment]
Unfortunately, this is not only a normalize problem, other styles will need to be tweaked to have a better experience on mobile. For example, `.docs-section` is set to `width: 75%`, etc.

In addition to tweaking the white-space behaviors, we'll also need to update the overall style for code blocks on mobile.

**Comment by jonbellah** [comment]
This was resolved in https://github.com/10up/Engineering-Best-Practices/pull/76
