### ISSUE TITLE
'tabindex' recommendation should be reconsidered

### ISSUE THREAD

**Issue by andrewmowe** [10up/Engineering-Best-Practices#65]
The use of the tabindex attribute should not be considered the primary approach to keyboard accessibility. As Joe Dolson points out in [this article](https://www.joedolson.com/2007/07/pseudo-accessibility/) it often does more harm than good. tl;dr: Planning a logical document structure prevents having to use tabindex all over the place, allowing you to use it only when needed.

**Comment by jonbellah** [comment]
This is interesting. The W3C spec still points towards recommending the use of tabindex, but I do agree this provides a cleaner, better practice in general. @tlovett1 @tddewey thoughts?

**Comment by jonbellah** [comment]
Adding @kdo and @zzramesses to this thread.

**Comment by helen** [comment]
I would strongly recommend that only tabindex values of 0 and -1 be used, for adding and removing from tabbable elements. Having taborder be different from DOM order is not a good idea.

**Comment by tddewey** [comment]
I agree that it's a use sparingly thing, so as Helen said, recommend against using it. In addition it can cause a maintainability nightmare.

**Comment by tlovett1** [comment]
@JonBellah can you write a PR?

**Comment by andrewmowe** [comment]
I created a PR based on these sources:
https://www.joedolson.com/2007/07/pseudo-accessibility/
http://webaim.org/techniques/keyboard/tabindex

**Comment by helen** [comment]
:+1: to the PR.

**Comment by tlovett1** [comment]
#70 looks good.
