### ISSUE TITLE
Event Delegation

### ISSUE THREAD

**Issue by jonathantneal** [10up/Engineering-Best-Practices#73]
Regarding the [JavaScript section](https://10up.github.io/Engineering-Best-Practices/javascript/#event-delegation) for [Event Delegation](https://github.com/10up/Engineering-Best-Practices/blob/gh-pages/_includes/markdown/JavaScript.md#event-delegation); could its purpose be clarified?

If we are listening for a `click` event on an `<li>` element, is it because we intend to do something with that element? Something outside normal browser behavior (i.e. what `<a>` or `:hover` already provide us)? For instance, could it be an item in a shopping cart, or a parent in a drop-down menu?

If we plan to do something with the `<li>` element, would it be useful to provide a safer code example? The current example checks for the existence of `event.target`, but what if the actual target is a child of the `<li>`? This scenario would seem very likely. While more verbose, a safer example might be:

``` js
document.getElementById( 'menu' ).addEventListener( 'click', function( event ) {
    var currentTarget = event.currentTarget;
    var target = event.target;

    if ( currentTarget && target ) {
        while ( currentTarget.contains( target ) ) {
            if ( target.nodeName === 'LI' ) {
                // Do stuff with target!
            } else {
                target = target.parentNode;
            }
        }
    }
});
```

A more loose example could be:

```
document.getElementById( 'menu' ).addEventListener( 'click', function( event ) {
    var target = event.target && event.target.closest( 'li' );

    if ( target ) {
        // Do stuff!
    }
});
```

While straight to the point, the above example uses [closest](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest), which to support Safari and older IE would require a 270B [polyfill](https://github.com/jonathantneal/closest).

Thoughts?

**Comment by tlovett1** [comment]
The intent is not to say we should not listen for events on the actual element rather delegate event listening to a parent if you need to detect things on a bunch of children.

Regarding the target issue, I agree. Can you open up a PR for the first example? I think we should leave out the polyfill.
