### ISSUE TITLE
Project Structure should discuss using add_theme_support() for decoupling.

### ISSUE THREAD

**Issue by QWp6t** [10up/Engineering-Best-Practices#75]
For our projects [Sage](https://github.com/roots/sage/blob/master/lib/config.php#L10-L14) and [Soil](https://github.com/roots/soil#modules), we use `add_theme_support()` to decouple the theme and the plugin. Removing the plugin (Soil) does not result in any errors, and changing the theme (Sage) does not result in any errors. This is another approach for decoupling code using standard WordPress paradigms, and I think it is worth mentioning.

**Comment by tlovett1** [comment]
I agree this is something worth mentioning. Take a crack with a PR?

**Comment by dsawardekar** [comment]
@tlovett1 PR is #144
