### ISSUE TITLE
Headings are feeling a little undifferentiated 

### ISSUE THREAD

**Issue by saltcod** [10up/Engineering-Best-Practices#77]
I'm finding that headings are bleeding together a bit for me. Adding some weight and a keyline on the pages' primary section headings (h3) might help. 

I've got this done in my local branch, but I'd like to have some feedback before committing. 

Thanks!
![after](https://cloud.githubusercontent.com/assets/105593/7634834/00315ed4-fa38-11e4-9c42-1168827c9be5.jpeg)
![before](https://cloud.githubusercontent.com/assets/105593/7634833/00308ec8-fa38-11e4-87d3-6c86d0cd2068.jpeg)

**Comment by DrewAPicture** [comment]
I agree that adding some weight to the headings could really help visually break up the content. I'm either way on the keyline, looks good though.

**Comment by jonbellah** [comment]
This is something I've thought about a lot, as well. I like these changes. I'm also a fan of the keyline.

+1

**Comment by tlovett1** [comment]
Looks good to me. Feel free to create the PR.

**Comment by dana-ross** [comment]
Headings are looking much better & consistent than when this issue was raised. Let's go ahead and close this one out.
