### ISSUE TITLE
Update BASE_PATH so that it always references the correct environment

### ISSUE THREAD

**Issue by jonbellah** [10up/Engineering-Best-Practices#80]
Currently, the BASE_PATH always points to the live site. This leads to some confusion when working on the site locally ("WHY ARENT MY STYLES UPDATING!?"). 

Not sure yet what the best approach is, but will start looking into it when I have a little more free time.

**Comment by tlovett1** [comment]
+1000

**Comment by jonbellah** [comment]
Let's not reinvent the wheel. https://github.com/10up/Engineering-Best-Practices/pull/93 just removes references to {{HOME_PATH}} in the asset URLs, and instead references local assets.

**Comment by jonbellah** [comment]
Fixed with #93 merge.
