### ISSUE TITLE
Markup page conflicts with PHP page

### ISSUE THREAD

**Issue by mikemcguire** [10up/Engineering-Best-Practices#81]
Not to be nit picky... Mark-up page says "Use colon syntax for PHP loops and conditionals so that it's easier to see when a certain loop ends within the block of markup."  But all of the code examples on the PHP page used bracket syntax?  Make up your mind 10up!

**Comment by lkwdwrd** [comment]
I believe that the difference is the context.

When in blocks of pure PHP, bracket syntax is easier to follow and should be used. This should not happen in an HTML template file, though, only in true PHP files. When working on a template file where PHP is being sprinkled in here and there to make it dynamic, colon syntax is easier to follow when wrapped in opening and closing `<?php ?>` tags. There should be a definite distinction between the two contexts when writing code.

This could be made more clear in the document.

**Comment by mikemcguire** [comment]
AH ok, that makes perfect sense to me. I agree it could be made more clear.
