### ISSUE TITLE
Optimize Readability confusing markup

### ISSUE THREAD

**Issue by elliott-stocks** [10up/Engineering-Best-Practices#84]
In the section Optimize Readability it sates; 

> When mixing PHP and HTML together, indent PHP blocks to match the surrounding HTML code.

Does this mean the PHP blocks should be aligned the same as the HTML markup? Or, should the PHP blocks be indented, as they would be if it was purely HTML?

For example the last code block shows -

```
<ul>
<?php foreach( $things as $thing ) : ?>
<li><?php echo esc_html( $thing ); ?></li>
<?php endforeach; ?>
</ul>
```

But from reading the above statement I feel it should look similar to this instead -

```
<ul>
    <?php foreach( $things as $thing ) : ?>
        <li><?php echo esc_html( $thing ); ?></li>
    <?php endforeach; ?>
</ul>
```

Is the statement misleading, or am I missing something?

**Comment by morganestes** [comment]
When I look at mixed PHP/HTML, I expect to see it formatted as the second example for ease of reading. When I let my IDE format the first code block according to the installed WP Coding Standards checks, it creates the second block.

I agree with @elliott-stocks that the second, indented format makes better sense.

**Comment by tlovett1** [comment]
I prefer the second too.

**Comment by lkwdwrd** [comment]
Yep, the language is intended to create the second block.

Luke Woodward – Engineering Manager
10up Inc. http://10up.com | luke.woodward@10up.com | @lkwdwrd
