### ISSUE TITLE
Changelogs?

### ISSUE THREAD

**Issue by bhubbard** [10up/Engineering-Best-Practices#88]
Was curious how your team handles changelogs for best practice? Thought this would be great to have in your best practices. 

Similar to http://keepachangelog.com perhaps?

**Comment by stevegrunwell** [comment]
I'm in full support of this :+1: 

Generally speaking we have a whole lot of projects that have been written throughout the years with varying degrees of formal change logs, but [KeepAChangelog](http://keepachangelog.com/) does appear to be the prevailing (and a sensible) standard to follow.
