### ISSUE TITLE
Address how and when to use PostCSS

### ISSUE THREAD

**Issue by jonbellah** [10up/Engineering-Best-Practices#89]
On the heels of a discussion from today, I'd like to possibly add more discussion around some specific Grunt tools - in this case, specifically PostCSS.

Sass remains our preprocessor of choice, but PostCSS presents some interesting extensions that can be very useful. For example, Autoprefixer is no longer supported as a standalone Grunt plugin and now lives on as a PostCSS plugin.

To be clear: while PostCSS is a "preprocessor" in name, it will not replace Sass (certainly not yet, at least), which is what we should cover in our Best Practices. Some of the "how" and "when" around using PostCSS.

Opening this issue as a reminder to myself to take a stab at a PR, but also to open this up for further discussion from any interested folks.

**Comment by tddewey** [comment]
This may be an arbitrary distinction, but I see PostCSS as a tool to support older browsers. It allows front-end engineers to write standards-based CSS, but have the "older browser fallbacks and workarounds" taken care of by PostCSS.

The classic example is autoprefixer, which allows us to write standards based css and then have vendor prefixes applied. Another somewhat trivial example might be to allow us to use the more correct double-colon notation for pseudo elements, but have PostCSS re-write them as single colons if we are supporting IE8.

To contrast: while PostCSS can allow CSS to be extended beyond current standards, we won't use it in this way, that will remain the realm of Sass. For example, with PostCSS you could create a syntax allowing for mixins or nesting. Until those items become part of CSS spec, we won't use PostCSS to implement them.

For things outside of CSS spec, we can use Sass. Sass is active and well-used. There are lots of resources — including full documentation — and the language is well supported.

For things within CSS spec, we can use Sass to support older browsers, but should prefer PostCSS.

**Comment by lkwdwrd** [comment]
Completely agree with Taylor Dewey here. Sass for extending CSS
functionality, PostCSS for writing in a more modern standards compliant
way. Well said.

On Tuesday, July 14, 2015, Taylor Dewey notifications@github.com wrote:

> This may be an arbitrary distinction, but I see PostCSS as a tool to
> support older browsers. It allows front-end engineers to write
> standards-based CSS, but have the "older browser fallbacks and workarounds"
> taken care of by PostCSS.
> 
> The classic example is autoprefixer, which allows us to write standards
> based css and then have vendor prefixes applied. Another somewhat trivial
> example might be to allow us to use the more correct double-colon notation
> for pseudo elements, but have PostCSS re-write them as single colons if we
> are supporting IE8.
> 
> To contrast: while PostCSS can allow CSS to be extended beyond current
> standards, we won't use it in this way, that will remain the realm of Sass.
> For example, with PostCSS you could create a syntax allowing for mixins or
> nesting. Until those items become part of CSS spec, we won't use PostCSS to
> implement them.
> 
> For things outside of CSS spec, we can use Sass. Sass is active and
> well-used. There are lots of resources — including full documentation — and
> the language is well supported.
> 
> For things within CSS spec, we can use Sass to support older browsers, but
> should prefer PostCSS.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/10up/Engineering-Best-Practices/issues/89#issuecomment-121332695
> .

## 

Luke Woodward – Engineering Manager
10up Inc. http://10up.com | luke.woodward@10up.com | @lkwdwrd

**Comment by jonathantneal** [comment]
PostCSS best resembles a **build tool**, and it might make sense for us to address it that way.

---

Sass is something something.

We use the Sass syntax help us to write commonly-repeated patterns once, and reuse those bits throughout a theme or plugin. It’s more efficient and far easier to maintain code this way. To compile Sass, we use RubySass or LibSass — and we find LibSass to be a much faster.

PostCSS exposes CSS as an abstract syntax tree (AST), allowing plugins to modify that tree before converting it back into CSS. Everything we perceive as being the work of PostCSS is really the work of a plugin.

We use PostCSS plugins like nextcss and autoprefixer to help us write the latest spec-driven CSS. These plugins handle the grunt work of future proofing our code; transforming it into more compatible CSS for all browsers.

Something something about being mindful of browser support. Something something about not using PostCSS plugins that compile Sass or do Sass-like things ala precss by yours truly.

---

Recommended reading: http://davidtheclark.com/its-time-for-everyone-to-learn-about-postcss/

**Comment by tlovett1** [comment]
@jonathantneal I think that's a good start. Would love to hear others weigh in.

**Comment by timwright12** [comment]
We're using this all the time now, closing this out.

**Comment by jonathantneal** [comment]
@timwright12, that’s great to read! Out of curiosity, which plugins do you use? Anything besides Autoprefixer?
