### ISSUE TITLE
(here|now)doc syntax

### ISSUE THREAD

**Issue by scottlee** [10up/Engineering-Best-Practices#92]
This topic came up internally recently and we thought it'd be worth pitching here as well: **should we consider offering advice on how, when, and if to use (here|now)doc syntax?**
## Take this code as example:

```
$image_html = <<<HTML
<div class="entry-thumbnail">
    <a href="$permalink>
        <img src="$image_src" />
    </a>
</div>
HTML;
return $image_html;
```
### Pro/Con
- Pro: Easy to read. (vs. `?><!-- some html here --><?php` )
- Con: Doesn't allow for truly **late** escaping.
- Con: Increased chance of mistake. One typo could cripple the code below.
- ??

CC: @daveross, @zrothauser

**Comment by mphillips** [comment]
Another option is to use output buffering. The syntax seems cleaner if you need to call functions or or add in other logic.

``` php
<?php
ob_start(); ?>

<div class="entry-thumbnail">
    <a href="<?php echo esc_url( $permalink ) ?>">
        <img src="<?php echo esc_url( $image_src ) ?>" />
    </a>
</div>

<?php
$image_html = ob_get_contents(); 
ob_end_clean(); ?>
```

But, I'm not sure we should standardize putting HTML in a variable because it is less secure and you can't escape late (right before output). Of course, there are edge cases that require putting HTML in a variable, but I don't think we should get into the habit of doing it frequently.

Sorry to butt in. :)

**Comment by scottlee** [comment]
You're totally not butting in, @mphillips. You're spot on, output buffering is very much in the same vein as *doc syntax.

**Comment by nicoladj77** [comment]
I usually use Heredoc and call any function i need before it because it avoids to enter exit/php, I really have hard times reading php inside html code. I think it's more readable than double quotes as you can avoid escaping double quotes. It basically becomes a logic-less templating engine.
I think that heredoc syntax is ok for 5-6 rows, not for bigger chunks of html.

**Comment by morganestes** [comment]
I like heredoc for the ease of reading, but the limitations of no late escaping and no processing inside (can't run a function call inside a heredoc) makes it pretty much unusable for the majority of WordPress use-cases. 

I think the no late escaping is problematic enough on its own to warrant not including heredoc as a recommended practice, but I do see value in including it as an alternative method with reasons to avoid the use of it.

**Comment by nicoladj77** [comment]
@morganestes i agree that inability to perform late escaping is a big problem. And it would be actually a reason to advice against using heredoc, or any kind of interpolation like double quotes, if we implement a static analysis tool to detect code which is not late escaped like WordPress VIP does.

**Comment by daveross** [comment]
Personally, I'd like to see us get HTML out of PHP code as much as possible. I've had problems at past jobs where front-end devs accidentally added 1 character to a block of PHP while editing some embedded HTML and brought sites down. PHP, HTML, and JavaScript should be in separate files.

Anything big enough for a heredoc is a candidate to be moved into its own file and pulled in  include()-ed from a function whose scope only contains the variables it needs, 

```PHP
// Ye olde template engine
function render_template( $template_name, $vars = array() ) {
  extract $vars;
  include "templates/{$template_name}.php"; // this should sanitize $template_name of course
}
```

Even better would be a proper template library like Mustache or Twig to get executable code out of our HTML completely. But I realize that's a big change and a departure from how the rest of the WordPress community works.

**Comment by dana-ross** [comment]
Personally, I'd like to see us get HTML out of PHP code as much as possible. I've had problems at past jobs where front-end devs accidentally added 1 character to a block of PHP while editing some embedded HTML and brought sites down. PHP, HTML, and JavaScript should be in separate files.

Anything big enough for a heredoc is a candidate to be moved into its own file and pulled in with `load_template()` or `include()`-ed from a function whose scope only contains the variables it needs.

``` PHP
// Ye olde template engine
function render_template( $template_name, $vars = array() ) {
  extract $vars;
  include "templates/{$template_name}.php"; // this should sanitize $template_name of course
}
```

Even better would be a proper template library like Mustache or Twig to get executable code out of our HTML completely. But I realize that's a big departure from how the rest of the WordPress community works.

**Comment by joeyblake** [comment]
This comment brought this to mind. Mustache rendering can be used on VIP, and is one of their plugins.

https://vip-svn.wordpress.com/plugins/lib/Mustache/

**Comment by saltcod** [comment]
Dave — I take it as a personal affront that you would even suggest such irresponsible behaviour from a front-end dev. 

I ask — nay — demand— that you issue an immediate, unequivocal public apology.

**Comment by nicoladj77** [comment]
I used Twig and it's fantastic. 
In theory i would prefer Mustache as it's logicless, but it lacks template inheritance. 
But i would love any templating engine other than plain php :smile:

**Comment by tlovett1** [comment]
Great discussion! I think late escaping is a total must. I love twig/mustache style things but haven't seen it done in WP in such a way that blends well with the structure, is easily maintainable, and easy for others to pick up,

**Comment by dkotter** [comment]
We recently used Mustache on a VIP project, both for loading the initial page, using Mustache PHP, and loading things inline, like infinite scroll, using Mustache JS. And it's true that Mustache doesn't have template inheritance, though they're supposedly working on that, but there are ways to get close to that, like partials.

Here's how we setup the Mustache PHP side of things, excluding the actual mustache view files and the code to get the post data: https://gist.github.com/dkotter/394347e2ef8c1f6ba53d.

I think it's a pretty nice and clean structure and easy to maintain, though it is much different then the typical WordPress way of doing templates. But I do agree that getting HTML out of PHP would be a great step to take and I would love to see more uses of a templating system in WordPress work.

**Comment by brs14ku** [comment]
+1 for Twig. I did a talk on Twig in WP at KC WordCamp this year. It's so nice keeping your PHP out of your markup.

**Comment by scottlee** [comment]
I'm kinda happy with what this conversation has turned into. Because I think ultimately no matter where we land, we're all seemingly in agreement that the intermixing of markup with PHP (specifically heredocs in this example) has more downsides than up.

But before we go down the road of Twig vs. Mustache, perhaps we should first add to the docs stating we do not recommend having markup within our PHP (via heredocs, nowdocs, etc)? We could even purposely leave it broad, recommending both Twig & Mustache as options.

FWIW, I too would like to see us starting using a templateing library. Internally though I'd love to see us choose one or the other. Instead of juggling both.

**Comment by morganestes** [comment]
I may be in the minority, but I'm okay with mixing PHP and HTML when appropriate, especially since that's the intended purpose of the language. The question I have is how best to do it, and heredocs don't seem to be that way for WordPress. That leaves things like `printf()` and its possible overuse, or breaking out of the PHP script for regular HTML and inserting PHP inline for escaped text and values (which can be difficult to read), or `echo`-ing strings (which is ugly but useful for caching HTML strings).

On templates: I like 'em, but unless we're trying to diverge from core and its mixed PHP+HTML style I think we should have the discussion but avoid putting anything into our docs until we can say definitively what we're recommending.

**Comment by dana-ross** [comment]
> But before we go down the road of Twig vs. Mustache, perhaps we should first add to the docs stating we do not recommend having markup within our PHP (via heredocs, nowdocs, etc)? We could even purposely leave it broad, recommending both Twig & Mustache as options.

I think that's a great first step, and it leaves the door open to whatever technologies we decide to experiment with or standardize on.

Scott, let's try to find some time after this week's wild ride to draft up something.

**Comment by stevegrunwell** [comment]
While I agree that Heredoc can make late-escaping more difficult, there are certainly scenarios where it can be extremely helpful for string concatenation or patterns (especially if whitespace is significant, such as generating code samples). It's also super helpful when stubbing out test responses in unit tests:

``` php
$response = <<<EOT
<?xml version="1.0">
<some-node>
  <item>
    <prop value="val" />
  </item>
</some-node>
EOT;

WP_Mock::wpFunction( 'wp_remote_retrieve_body', array(
  'times'  => 1,
  'return' => $response,
) );
```

XML aside, I can think of at least two major migration projects I've worked on at 10up where the format of imported content was significant, and Heredoc made writing those tests far easier.

I'd recommend we avoid making a blanket "don't use Heredoc" statement. Instead, perhaps it would be best to take an approach [similar to what we've said about `cache_results` in Efficient Database Queries](https://10up.github.io/Engineering-Best-Practices/php/#efficient-database-queries): there may be scenarios where Heredoc is appropriate, but if you're using it regularly you might be doing it wrong.

**Comment by ericmann** [comment]
> XML aside, I can think of at least two major migration projects I've worked on at 10up where the format of imported content was significant, and Heredoc made writing those tests far easier.

FWIW, the general recommendation _against_ heredoc syntax orbits almost exclusively around security and internationalization. It's not just difficult to apply internationalization and escaping to the content of a heredoc, it's difficult to code review things later down the road. Yes, it's often simpler to have a large block of markup in a heredoc, but it can be very difficult to review the code _later_ if changes are introduced that obscure when/where any dynamic values are being escaped or translated/escaped.

As for heredocs in tests ... tests are local developer tools and can fit a completely different set of requirements. Case-in-point, the minimum PHP version requirement for WP_Mock and PHPUnit is _higher_ than that for WordPress in general, so there's a lot that you can do syntax-wise in a test that wouldn't fly in a theme or a plugin. The same goes for migration code when it's intended for a server completely under the developer's control.

> I'd recommend we avoid making a blanket "don't use Heredoc" statement.

I agree. Blanket statements are bad. However, I think strongly advising _against_ heredocs in theme/plugin code meant for distribution (read: not tests or migration/developer CLI routines) would be a good balance.

**Comment by dana-ross** [comment]
This was a great discussion. I've noticed 10up engineers have pretty much abandoned heredoc/nowdoc so I'm going to close this out.
