### ISSUE TITLE
PHP indentation in code is getting dropped

### ISSUE THREAD

**Issue by westonruter** [10up/Engineering-Best-Practices#99]
For instance, look at https://10up.github.io/Engineering-Best-Practices/markup/#examples 

<img width="989" alt="markup_md_-_engineering-best-practices_-____projects_vvv_www_engineering-best-practices__and_10up_engineering_best_practices" src="https://cloud.githubusercontent.com/assets/134745/9422879/5b481f6a-485d-11e5-8775-60092ff28827.png">

**Comment by tlovett1** [comment]
Yep, @JonBellah and I spent a few minutes trying to fix this one to no avail (yet). It would be nice to correct though :) We will loop back to it.
